# Site settings
title: How i code
email: ziexe0@gmail.com
description: > # this means to ignore newlines until "baseurl:"
    Универсальность и слабоумие
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://intey.github.io" # the base hostname & protocol for your site
# twitter_username:
github_username:  intey
# Build settings
markdown: kramdown
